# Encoding Categorical Data

Encoding categorical data is basicallly converting categorical data to numerical data as the ML models cant read strings. They can only read numbers, so we need to change catehorical data to numerical data.

Types of encoding:

- Ordinal Encoding

- Label Encoding

- One Hot Encoding

## Ordinal Encoding

Ordinal Encoding is a data preprocessing technique used to convert categorical data into numerical values while preserving the inherent order or ranking between those categories.

It is typically performed during the feature engineering or data cleaning stage of a machine learning pipeline, specifically when:

- The data is "Ordinal": Categories have a natural, logical sequence (e.g., Education Level: High School < Bachelor's < Master's < PhD).

- Dimensionality is a concern: You want to avoid the "curse of dimensionality" caused by techniques like One-Hot Encoding, which create a new column for every single category.

- Tree-based models are used: Algorithms like Decision Trees, Random Forests, and XGBoost often handle ordinal integers very effectively without needing complex transformations.

Advantages:

- Preserves Order: It maintains the mathematical relationship between levels (e.g., the model knows 'High' is "more" than 'Low').

- Memory Efficient: It creates only one column of integers, keeping the dataset compact.

- No "Dummy Variable Trap": Unlike One-Hot Encoding, it doesn't create multi-collinearity issues.

Disadvantages

- Assumes Equal Spacing: It implies the distance between 1 and 2 is the same as between 2 and 3, which may not be true (e.g., the jump from "Neutral" to "Satisfied" might be bigger than from "Satisfied" to "Very Satisfied").

- Misleading for Linear Models: Linear and Logistic regressions might struggle if the relationship between the ranks isn't actually linear.

- Not for Nominal Data: If you use it on categories without order (like Colors: Red, Blue, Green), the model might think "Green" is "better" than "Red" just because 3 > 1.

In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Create a dummy dataset
data = {
    'City': ['New York', 'London', 'Paris', 'New York', 'London'],
    'Education_Level': ['High School', 'Bachelor', 'PhD', 'Master', 'Bachelor'],
    'Experience': [1, 5, 10, 7, 3]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
display(df)

Original DataFrame:

       City Education_Level  Experience
0  New York     High School           1
1    London        Bachelor           5
2     Paris             PhD          10
3  New York          Master           7
4    London        Bachelor           3

Now, let's apply Ordinal Encoding to the 'Education_Level' column. Since there's a natural order to education levels, we'll define that order. If no order is specified, `OrdinalEncoder` will assign integer values based on the sorted unique values in the column.

In [2]:
# Define the order for 'Education_Level' (important for ordinal data)
education_order = ['High School', 'Bachelor', 'Master', 'PhD']

# Initialize the OrdinalEncoder with the specified categories order
encoder = OrdinalEncoder(categories=[education_order])

# Apply ordinal encoding to the 'Education_Level' column
df['Education_Level_Encoded'] = encoder.fit_transform(df[['Education_Level']])

print("DataFrame after Ordinal Encoding:")
display(df)

DataFrame after Ordinal Encoding:

       City Education_Level  Experience  Education_Level_Encoded
0  New York     High School           1                      0.0
1    London        Bachelor           5                      1.0
2     Paris             PhD          10                      3.0
3  New York          Master           7                      2.0
4    London        Bachelor           3                      1.0

## Label Encoding

Label Encoding is a technique used to convert categorical labels (text) into numerical values (integers). Each unique category is assigned an arbitrary number, typically starting from 0.

Unlike Ordinal Encoding, Label Encoding does not necessarily imply a hierarchy; it simply translates a name into a number so that a machine learning algorithm can process it.

When is it done?

Label Encoding is used almost exclusively for the Target Variable ($y$).

- Target Classification: When your output column contains categories like "Yes/No," "Spam/Ham," or "Cat/Dog/Bird."

- Preprocessing Stage: It is done after data cleaning but before training the model, ensuring the machine learning algorithm (which speaks in numbers) can understand the classes it needs to predict.

Advantages (Pros)
- Simplicity: It is incredibly easy to implement and understand.

- Storage Efficiency: It requires very little memory because it replaces long strings with small integers.

- High-Cardinality Friendly: It works well when you have hundreds of unique categories in a target variable, as it keeps everything in a single column rather than creating hundreds of new ones (like One-Hot Encoding would).

- Algorithm Compatibility: Most classification algorithms in libraries like Scikit-Learn require numerical targets to calculate loss functions and gradients.

Disadvantages (Cons)

- Implied Hierarchy (The "Order" Problem): This is the biggest drawback. Algorithms might mistakenly assume that a category labeled "2" is greater or more important than a category labeled "0."

- Limited to Target Variables: In professional machine learning, using Label Encoding on input features ($X$) is generally discouraged because the arbitrary numbering can confuse models like Linear Regression or SVMs.

- Mathematical Bias: Because the numbers are arbitrary, the distance between categories (e.g., $2 - 1 = 1$) has no real-world meaning, which can introduce noise into the model's logic.

In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Create a dummy dataset for Label Encoding
data_label = {
    'Fruit': ['Apple', 'Banana', 'Orange', 'Apple', 'Mango'],
    'Color': ['Red', 'Yellow', 'Orange', 'Red', 'Yellow'],
    'Price': [10, 5, 12, 11, 8]
}
df_label = pd.DataFrame(data_label)

print("Original DataFrame for Label Encoding:")
display(df_label)

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Apply Label Encoding to the 'Fruit' column
df_label['Fruit_Encoded'] = label_encoder.fit_transform(df_label['Fruit'])

print("\nDataFrame after Label Encoding on 'Fruit' column:")
display(df_label)

# You can also see the mapping of classes to their encoded values
print("\nClasses and their encoded values for 'Fruit':")
for i, item in enumerate(label_encoder.classes_):
    print(f"{item}: {i}")

Original DataFrame for Label Encoding:

    Fruit   Color  Price
0   Apple     Red     10
1  Banana  Yellow      5
2  Orange  Orange     12
3   Apple     Red     11
4   Mango  Yellow      8

DataFrame after Label Encoding on 'Fruit' column:

    Fruit   Color  Price  Fruit_Encoded
0   Apple     Red     10              0
1  Banana  Yellow      5              1
2  Orange  Orange     12              3
3   Apple     Red     11              0
4   Mango  Yellow      8              2

Classes and their encoded values for 'Fruit':
Apple: 0
Banana: 1
Mango: 2
Orange: 3

## One Hot Encoding

One-Hot Encoding is a process that converts categorical variables into a series of binary columns (1s and 0s). For every unique category in a column, a new column is created. If a row belongs to a specific category, it gets a 1 in that category’s column and a 0 in all others.

When is it done?

One-Hot Encoding is performed during Feature Engineering on the input variables ($X$). It is used when:

- The data is Nominal: Categories have no rank (e.g., Apple, Banana, Cherry).

- The number of categories is low to moderate: If you have thousands of unique categories, this method can make your dataset too "wide" and slow down training.

- Using Linear or Distance-based models: Models like Linear Regression, SVM, and KNN need this because they cannot interpret the "distance" between categories correctly if they are represented as 1, 2, or 3.

Advantages (Pros)

- No False Hierarchy: Unlike Label/Ordinal encoding, it doesn't trick the model into thinking "Yellow (2)" is greater than "Red (1)." All categories are treated as mathematically equal.

- Better for Linear Models: It allows models to assign a specific weight (coefficient) to each category individually.

- Easy Interpretation: It is very clear which feature is influencing the prediction (e.g., "If Country_USA = 1, then Price increases").

Disadvantages (Cons)

- Curse of Dimensionality: If a feature has 100 unique categories, One-Hot Encoding adds 100 new columns to your dataset, which can significantly increase computational costs.

- Sparse Matrix: It creates a dataset filled mostly with zeros, which is inefficient for memory storage.

- Multicollinearity (Dummy Variable Trap): Since the columns are correlated (if you know all other columns are 0, the last one must be 1), it can confuse some statistical models.
  - Fix: Usually, we drop one column (e.g., using drop_first=True) to prevent this.

In [4]:
import pandas as pd

# Create a dummy dataset for One-Hot Encoding
data_ohe = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Laptop', 'Mouse'],
    'Category': ['Electronics', 'Electronics', 'Peripherals', 'Electronics', 'Electronics'],
    'Country': ['USA', 'UK', 'USA', 'Germany', 'UK']
}
df_ohe = pd.DataFrame(data_ohe)

print("Original DataFrame for One-Hot Encoding:")
display(df_ohe)

# Apply One-Hot Encoding to the 'Product' and 'Country' columns
df_ohe_encoded = pd.get_dummies(df_ohe, columns=['Product', 'Country'], drop_first=True, dtype=int)

print("\nDataFrame after One-Hot Encoding:")
display(df_ohe_encoded)

# Note: drop_first=True is used to avoid multicollinearity (the 'dummy variable trap')
# and dtype=int ensures the new columns contain integers (0s and 1s) instead of booleans.

Original DataFrame for One-Hot Encoding:

    Product     Category  Country
0    Laptop  Electronics      USA
1     Mouse  Electronics       UK
2  Keyboard  Peripherals      USA
3    Laptop  Electronics  Germany
4     Mouse  Electronics       UK

DataFrame after One-Hot Encoding:

      Category  Product_Laptop  Product_Mouse  Country_UK  Country_USA
0  Electronics               1              0           0            1
1  Electronics               0              1           1            0
2  Peripherals               0              0           0            1
3  Electronics               1              0           0            0
4  Electronics               0              1           1            0